name: Create status check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: hub example
        shell: bash
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
      - name: create status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.head_ref == 'release' && github.base_ref == 'main'
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/tyrwzl/workflow/statuses/${GITHUB_SHA} \
          -d '{"state":"success", "target_url": "", "status": "completed", "description": "OK",   "context": "target check" }'
      - name: CreatePullRequest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.head_ref != 'release' && github.base_ref == 'main'
        run: |
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/tyrwzl/workflow/statuses/${GITHUB_SHA} \
          -d '{"state":"failure", "target_url": "", "status": "completed", "description": "OK",   "context": "target check" }'
